services:
  adult:
    platform: linux/amd64
    container_name: adult-app
    image: devitools/hyperf:8.3-dev
    working_dir: /opt/www
    volumes:
      - ./:/opt/www
    environment:
      - SONAR_TOKEN=${SONAR_TOKEN:-undefined}
    entrypoint: [ 'tail', '-f', '/dev/null' ]
    restart: on-failure
